// PROOF OF CONCEPT — album data is baked in at build time (see albumPhotos.js,
// generated by scripts/fetch-photos.sh). Future version: store album links in a
// database, manageable through an admin portal, and render from there instead.
import { useEffect, useRef, useState } from 'react'
import AccordionGallery from '../components/AccordionGallery.jsx'
import { ALBUMS } from './albumPhotos.js'

const thumb = (src) => src.replace('=w1200', '=w800')
const SETTLE_MS = 280 // hover linistit atat => gridul revine; miscari rapide tin gridul stins

export default function Evenimente() {
  // null = all events; otherwise index into albums with photos
  const [open, setOpen] = useState(null)
  // albumul randat efectiv + stare fade; la hover rapid, shown se comite
  // doar dupa SETTLE_MS de liniste, deci gridul ramane stins intre switchuri
  const [shown, setShown] = useState(null)
  const [faded, setFaded] = useState(false)
  const prevOpen = useRef(open)
  const timer = useRef(null)

  useEffect(() => {
    if (prevOpen.current === open) return
    prevOpen.current = open
    setFaded(true)
    timer.current = setTimeout(() => {
      setShown(open)
      setFaded(false)
    }, SETTLE_MS)
    return () => clearTimeout(timer.current)
  }, [open ])

  useEffect(() => () => clearTimeout(timer.current), [])

  const withPhotos = ALBUMS.filter((a) => a.photos.length > 0)
  const sections = shown === null ? ALBUMS : [withPhotos[shown]]

  return (
    <main className="page">
      <header className="hero">
        <h1>evenimente</h1>
        <p className="lede">
          Conferințe de deschidere și albume foto din fiecare an —
          click pe un eveniment pentru fotografiile lui.
        </p>
      </header>

      <section className="flush">
        <AccordionGallery
          items={withPhotos.map((a) => ({
            image: thumb(a.photos[0]),
            label: a.title,
            alt: a.title,
          }))}
          trigger="hover"
          accentColor="#f4f0f0"
          textColor="#f4f0f0"
          overlayColor="#000000"
          height={380}
          onSelect={setOpen}
        />
      </section>

      <div className={'grid-fade' + (faded ? ' is-out' : '')}>
      {sections.map((a) => (
        <section key={a.href}>
          <div className="masonry">
            {a.photos.map((src, i) => (
              <figure key={src}>
                <a href={a.href} target="_blank" rel="noreferrer">
                  <img
                    src={src}
                    alt={`${a.title} — fotografia ${i + 1}`}
                    loading="lazy"
                    decoding="async"
                    referrerpolicy="no-referrer"
                  />
                </a>
              </figure>
            ))}
          </div>
          <p>
            <small>
              {a.meta} —{' '}
              <a href={a.href} target="_blank" rel="noreferrer">
                albumul complet în google photos
              </a>
            </small>
          </p>
        </section>
      ))}
      </div>
    </main>
  )
}
