#!/bin/sh
# Scrape public Google Photos shared albums into src/pages/albumPhotos.js
# Re-run to refresh: sh scripts/fetch-photos.sh   (needs curl + python3)
# Recipe: mobile UA + http1.1 (desktop UA gets a JS interstitial bot-wall).
# Photo URLs get '=w1200' (masonry-friendly). Use referrerpolicy="no-referrer" on <img>.
set -u
cd "$(dirname "$0")/.."

python3 - "$@" <<'EOF'
import re, subprocess, sys, time

albums = [
    ("2024–2025 · conferința de deschidere", "https://photos.app.goo.gl/u4m1GLngCrkgTHQt5"),
    ("2023–2024 · conferința de deschidere", "https://photos.app.goo.gl/rKqrnikiraQMJFDr7"),
    ("2024 · ziua culturii naționale, 15 ianuarie", "https://photos.app.goo.gl/sb59Z27vJnb1PA1Z7"),
    ("2024 · informat, 12 ianuarie", "https://photos.app.goo.gl/ZEyFPK9xZJpjvVVH8"),
    ("2023 · poze webtooncnu", "https://photos.app.goo.gl/ufnWGmaQ6Yzi2HPd9"),
]
UA = "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1"

def get(url):
    return subprocess.run(
        ["curl", "-sL", "--http1.1", "-m", "60", "-A", UA, url],
        capture_output=True, text=True, timeout=120).stdout

# usage: sh scripts/fetch-photos.sh ["titlu|link" ...] — no args = built-in list
cli = []
for a in sys.argv[1:]:
    if "|" in a:
        t, h = a.split("|", 1)
        cli.append((t.strip(), h.strip()))
albums = cli or albums

out = ["// auto-generated by scripts/fetch-photos.sh — do not edit by hand", "export const ALBUMS = ["]
for title, href in albums:
    try:
        html = get(href)
        ids = sorted(set(re.findall(r"https://lh3\.googleusercontent\.com/pw/[A-Za-z0-9_-]+", html)))
    except Exception as e:  # ponytail: broken album = empty grid, keep going
        print(f"FAIL {title}: {e}", flush=True)
        ids = []
    else:
        print(f"OK {title}: {len(ids)} photos", flush=True)
    photos = ",\n      ".join(f'"{i}=w1200"' for i in ids)
    out.append(
        "  {\n"
        f'    title: "{title}",\n'
        f'    href: "{href}",\n'
        f'    meta: "{len(ids)} fotografii · album google photos",\n'
        f"    photos: [\n      {photos}\n    ],\n"
        "  },"
    )
    time.sleep(3)
out.append("]")
open("src/pages/albumPhotos.js", "w").write("\n".join(out) + "\n")
EOF
